branches:
  - main
  - master
ci: true
debug: true
dryRun: false
tagFormat: '${version}'

preset: 'conventionalcommits'
gitlabUrl: 'https://gitlab.com/'

verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/gitlab'

analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    releaseRules:
      - type: 'feat'
        release: 'minor'
      - type: 'fix'
        release: 'patch'
      - type: 'docs'
        scope: 'README'
        release: 'patch'
      - type: 'chore'
        scope: 'deps'
        release: 'patch'
      - type: 'perf'
        release: 'patch'
      - type: 'refactor'
        release: 'patch'

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    preset: 'conventionalcommits'
    presetConfig:
      types:
        - type: 'feat'
          section: '🚀 Features'
        - type: 'fix'
          section: '🐛 Bug Fixes'
        - type: 'docs'
          section: '📚 Documentation'
        - type: 'chore'
          section: '🔧 Maintenance'
        - type: 'perf'
          section: '⚡ Performance Improvements'
        - type: 'refactor'
          section: '♻️ Code Refactoring'

prepare:
  - path: '@semantic-release/changelog'
  - path: '@semantic-release/exec'
    cmd: 'VERSION=${nextRelease.version} ./scripts/update-readme.sh'
  - path: '@semantic-release/git'
    message: 'chore(release): Publishing Release: ${nextRelease.version}'
    assets:
      - README.md
      - CHANGELOG.md

publish:
  - path: '@semantic-release/gitlab'

success: false
fail: false
